#lang r7rs
(import (scheme base)
        (scheme write)
        (a-d pattern-matching kmp))

(define input-string "SSSXSSMSXMMAXXAXMSSMSSMSXMASXXMXMMXMSXSMXMMSASXMMAMMMMMXSAXMAMASMASASXSXMMMSMAXMSAMXAAXXXAMXSAMSAAMMXASXMXXXXASXMMSMMMMMMMSMMSAMSSSMXSMMXSXM
MXMAMMMSAAMSSSXSMMMMMAMMMXMMXXAAXMAMMAASMSXMASAXSXMAAXAAAMAMXSXXMASMMAMXMAAAXXMASXSSMXAMSXMAMXXSMXXAMXXAXMSMMMMAAAXXAAAXAAAAXSAMMASXAMXXAMAS
XAMAMSAMMMMAAMAAXAAMSAMXSAAXSSSMSSSSMXMAXMAMSMXMAASXMSMMSXMMXAMXMASXMAXAMMXSSMAMSAMXAXMMAMXXXXXMASXMMASXMAAXAASXMASXSSSSMSXSMXAMMMMMMSSMMSAM
SXSASMMSXAMMSMMMSSSMSXSASMSXMAMAAXAAASXMASAMXASMSMMAMSMXXASMMSMXMASMSSMMXSAAMASXMMMASMXMAXMSASXMAMMMSXMASMMSSXSXXXMAMAMMAMAMASMMMMAAAAXAAXXS
MXMXMAXXMXXAAAXAAAAAXAMAMAMMMAMMMMSMMMASXMASMXMAXXSAMMMMSMMAAAAAMMXAAAASAMMSMAMASXMAMMXSSSMXMSAAAXAMXAXAMXMAXMMMXSMAMAMMAMMMXMMAASMSSMSMMMMA
MASMSMMMSMMSXMMXMMMMMMMSMAMSMXSAMXAXXSXMAMXXXXMXMMXMXSAAXXXMMSSXSAMSMSMMASAXMASXMAMMXSAMXAXXXSXMMSSSSSMXSXMASXMMAMSSSXSMMSASXAXSMMXAMXMAAASM
SAXXAMAAAAMAASXMSXAXXSAMSSMMMMSAMXXMASXMAMSXMMSSMMSAASMMSMMSAMMAMMMXAMXSAMMSSXMASMMXAMASXMMMMMAMXXAAAMAMSXMMMMMMAMAXMAMAMSASXSMMASAMXAXXXXMX
MXSSMSMSXSMMXMAAXXAMAMAXAXAASAMXMXMAXXMMAMSAMASAAAMMMSXMAMAMASMXMSMMXMAMXSAMXMSAMASMASAMAAAAASAMXMMMMMSMSASAXAASMMSXMAMAMMAMAXXMAMXSSMSMSSSX
XMAAASMMAMAMSSMMMMSSXSMMMXMMSXXMSMMMSMAMSMSAMSSMMMSMMSXMXMMXXMMXAASMAMAMAMMMMMMXSAMAXMMMAMXSXXAXSMMXSXAAXAMASMMAAXAASASAMXAMMMSMAXAXAAAAAAAM
MASMMMAXAXAMXMASXXAAMMAAXMAMXXXAAAAAAXMXMASAMXMAMXSAMXASAMXMMASMSXMMXMAMMMXMAMSMAMSMSAMXSAMXMMSXAXMMMSMMMMMXMAASMMXXMAMMSSXSAASASASXMMMMMSMA
AMAMXSAMXSSMMXMMMMMSSSSMSAMSASMSMSMSSSXSMAMMXSXXMAXAXSXMXXMASAXXMMSXXSASMSSSMMXAMMSXMXMAXAMXAAMXAMXAMASAAXXXAXMAXSXSMAMXAMASMAMAMAMXMMXMAXAS
SSXSXMXMXSXAMXSAAMXMMAAXAXXMAMAMXMMXAXAXMXSMAMMAMSMSMMMMXSMMMAMXMASAAXAMAAAXMASMXMSAMSMMMAMMMMMAMXXMMAXMMMSMSMSXAXAMMMSMASAXMAXAMXMAXSAMSSMX
XMAMMSAMMSSSMAMMSMAMMSMMMMXMXMMMASXMXMXMAMAMMSMSXASAAAAMMMASMMMAXSMMMSSMMMSMSAXMASMAMAAXSSMXMASMMSSXMMSSMMSAAAXMMMAMAAAMXMMSXMXMXXSAXSMMMSAX
MMSMAXASMXAMMXMAMMAMXAMMXMXSAAASASAXMASAMSSSMSAXMXSMSMXSASAMAASMMMAMXAXMAMXAMMMMXMMAMMMAMMAMXASAAAMASAAMAAMSMSMMXMASMSXSXAMXMMASMMMXXXXAAMMM
XAASMSMMMMAMAAMASXMSMSAMAMMXXSXMASMMMSASAAAAAMMMMAMXMAAXMMAMMMSXAXSMMXXMMAMXAXSASASXSXMASMXMMMSMMMSAMMSSMMMXMAMMAMMSMMXAMXMAMSASAMAXXMSMSMXA
MXMSXAMSXXXMSXSASAXMAXMSASXMMMXMXMMAMAAMMMSMMMXSMXSAMMMMSMXSAMXXSXMASASXSXSXAASAXASAAXSASXSXMAXAAXMXSXMAMSASMMMSASMSASXMSSSMMAAXMMMSAAXAAXMX
SMMXMAMAMSAMXXMASMMMAMXSASMAMAXMAMMSSMXMAMXMXMXMAXMXXSAMXAASXXMAXXSAMMAAMAMMAMMMMMMMMMMMSMXAMSXSMXMMXASAMXMXAAASMSAMXMAMAAAXMMMMXMAXMMMMMMSA
SAMAMSMMAAASXMMAMXAXAXMMMMMSMAXMAMAXAXMSAMXMASXMSMXMASXSMMMSASASXAMASXMSMAMMXMAXAXXXXASXSAMSMMAMAASXMXMAMMXSSMMXAMAMMMMMMXMMMAMMAMSSSMSAAAMX
SAMMMAASMMMMMAMSSMSSSSMSSMSXMAMSAMMSSMMXAXAMASAXXAAXXMMMXAMXAMAMMAMAXAXXXSMMASMMSXMXMSMAMAMXASAMSMMAXSSMMMMMXASMMMASAAMXSAAXMAMXAMAAMASMSXXS
MAMXSSXMSMSAMXMAAMMAMXAAAXSAMXMMAMXAMXAXSSSMSSXMMSMSMAASXSSMAMAMASMMMSMMMMASASAMXAAAMAMMMAMMAMSMXMMSMAAXSAXXMASAMSMSMMSAXSXMMASXSMMSMAMAXMXS
SMMMXMAAAXSASMMSSMMAMMMMSXSXMAMSAMMAMMMMXAXXXMAMAAMXMSMSAMXMASASMXAAAMMSASMMAMAMSXXXSASXMAXMXMASXXAAMSMMSMSMSMMAMXASAMMMMXMAMMSAAMMAMXSAXAMX
AASXAMMSMXSXMAAAMXSSMMSAMASMSSXMMSSSMSXSMMMXMMAMMXMAMXAMXMAXXXASXXAMXSASXSASXSSMMMSMAASXSASMMMAMMMSSMXAAXXAMAASMMMXMAMAXAMAXSMMXMMSASMMMXSAA
SXMXXMAAMASMSMMMSAAAMASAMMMXAMASXMAXAAMXAXAASMSXSAMSSMMMSXSSSMAMMSMMXMAMAMXMAAXAXAAAMMMMMAXAAMASAAMAAMMMSSXSSMMAXMASXMMMSMMAAXMAXMSASXAAMMSS
MASMMMSXSXSAXXXXMMSSMAXAXSXMMSAMAMSMMMMXMMSMSAAAXAMAXAXAXAXAMMSMAAMMAMAMSMMMXMSMMMSXXMAXXASXSMASMSSMMSXAAXXAMXSXMAMXMAMAAAMXXMSXSMMMMXMXSXMX
XAMXSAMXAAMMXXAAXMAMMMSSMMMSAMAXAMXAXASAXAMAMMMSMXMMSSMSSMMAAXMMMSXSASAAAAMSMXMASXMXSSMSMXSAAMAXXAAXAAMMSSXMAXMMMXSMMAMSSXSMAAXXAXAXMAMSMAMM
MSXMMASAMXMAAMSMMMAMSAMXAAAMXSMMSSMXSASMMMMAMSAMXMSXMAAAAXSAMSMSAMMMXMMSSSMASMMASAMAXAMXMAMMMMSXMSMMMSASAMXMAMXAMXSASAXMMAAXMMSAMMSSSMSASAMA
XMASXMMMAMXMMXAAXMAXSXXSXMMSAMXAXAXAMMMXAAMAMMMMAMXASXSSSMSAXAAMASXSASMAAAXMSXMASAMXSAMXMMSXMAXMAMAMXAMMASXSASMXSASAMXSAMAMXMAXMXAMAMXXMMMXS
ASXMASAXSMMSMSSXMMMXMMMSXSASMSMSMMMXSAXSXSSMSAMSAMXXMAMAAASASMSMMMASASMSSMMXSAMXSAAMXMAXMXSASAMXASXMSXSXMAASAMAXMAXXMASAMMXMMXSXMXSAMSMSMSAX
MXASAMASXAAMMAAXSASAMXXSAMASASAMAASASMMMSMAAMAMSMMSXMAMAMXMXSMMXAMXMSMMAAXAXSASAXXMXAMMXMASAMXSMXSAAAMXMSMAMMMMMMSMMMXSMXSAAXMMAMXMAMMAAAMAS
SSMMXMXAMMMSMMSMSASXXSMMAMMMMMAMSMMASXXMAMMMMMMMMMAAXMASXXSASASAMXXMXMMMSMSASAMXSAXMASAAMASXSXMXAXMMMXAXXXMSASMSAXAXMAMXAXMSMXSAMAXMAMXMSMAM
XAMAMSSSXMAMAAXAMXMMMSASMMMSXMXMXAMSMAMMXXAXXAAXMASMMMAMMMMASAMXMMMSASAMXAXMMAMSAMXMAMXSMMSXMASMMXXXXMMSXSAMXXAMASXMMSSMMXMAMXMASASXSSSMMMAS
MXMAXAAMXMASXMMSMMAXAMXAAMXMASMXSAMMMSMMAMSSMSSSMXMASMAXSAMAMXMAXXAMMSASMXMXMMMXMASMASXMXXSASXMAMASXXAAXMASXMMMMMMMMAAAAAAMMSXSAMASAMXAAXSSS
MSSSMMSMXSXSAAAAMXMMMXMMMMAXXMMASAMXAAAMAXAAAAAAAXSMASXXSASAMSSXMMMSASAMMSXSASMXAMXSASAASMMMSAMSAASASMMXSAASAAXAAAXMMSSMSMSASMMXSAMMMSSMMMAM
MMAAMXXAMXAMMAMXMASASASAXSSMSAMASMSMSSSMMMSSMMSMMAMXMAMASXMXMAMMAAMMMMXMSAASAMAMSAXMSSMMMXAAXAMAMXSXSAMAMXXXMMXSSSXSAMXAAXMAMAMASAMXAAXMASAM
ASMMMXMAXMAMXXSXMASASAXXMXAASAMASAMAAAAXMAXAAAXMMMSAXAMMMSMXMASXMXMAMMMMMXMMAMAXMASMAXMSXSMSSSMAMXMASAMASXMSXSAMAMXASXMMMXSXSAMXXAMMMSSSMSAS
MMAXSXMXSSMSSXSASMMMMMMSMMMXMMMXMAMXMSMMMSSMMMMXAAMMXMXAAXMASASXASXMMASXMMSMXMMMAAMMASMXAXAAXAXAMXSASMSAXAMAASXMSMSSXMXXAAMASXSXSSMSXMAAASXM
XSMMMASAMAAAAAMAMAAXMAMXASXMAXSASMMSXMASAMAMSSSSMSXXAXXMSSMMMAMMXMAXMMXAAAMXSASMMMSAASAMXMMMSMSSSXMASAMXSSMMMMAAAAXXXSMMMSMAMAMXAASMAMSMMSAX
MMMXXAMXSMMMMMMSMMASXMMSXMAMAMXAMXAAASAMXXAMAAAXSAMSMSAMAMAMSSMSXMAMSSSSMMSASAMAASAMXXMAMXAXXXAAXMMAMAMAAXXXAMMSMMMMMAAXAXMXMAMMMMMXXMXMSXMS
AAMAMSSMMMMSXXXXAXASXSASMSMMXSMMMMASXMSMXMSMMSMMMXXAASXMAXAMXAASAXMASAAXMXMAMAMSMSMSSSXSASMAAMMSSSMSSXMMSSMSMXXAXAAAMMSMMXMAMMSMSMSSXMAXXAXX
XAMAXMAAXMASAMMSXMMSAMASAAXXAAAASXAXMAXXMAMAAMAMSMMMMMXSSSXSSMMMAMASXMXMSMMSSSMXASXAAXAMASMXMMAAXAAAAAXAAMXAMMSMSMSMSAMASASAMXAAAAMMMSSSSMMM
SSSSSXSMMMAMMAAAAXAMXMSMXMSMMSSMSMXSMAMMMMXMMSAMXXAXAMMMXAMXMAMXAMXMXAMMAAXAAAXMAMMXSMSMAMASXSXSSMMSSSMMMSSMSAXASMXAMAMAMXSXSSMMMSMXAMMAXAAX
AAAASAAMMMSSXSASXXMXMXXAXMXAAMXMXXMSMAMXAAMSASXSMSASASAMXMMXSAMSSSXSMSMSSSMMSMMMMSAMAAXMAMXMASXMXMMMAXXAXXMXMXSAMMMSMMMSMMXMAXSASAMMSSMAXSXS
SMMAMMMSAAXMAXAMAMXASAMMMMSSMSMXXMAXMSMXMXXMASASAMASXMXMASAAMXXSAMXXXAAAAAXAAAAAAAXAMMMASMXMXMMSAAAMMMSMMXMXAAMMMXAAXMAMASMMAMMXSASAAAMMMMSM
XXMXSXAXMMXSAMMMAXSAMAAMAMMAAAAXSXMMAMASXSMMAMAMSMAMAMSSMSAMMMMMMXMAXMMMXMMSSSMMSSMMSXSAMMAMASASXMXMXMAMMSSMSAMXAMMSXSAMSMAMSSSXMXMMSXMMAXMX
MXSASMMMSAAMXXXSXMMSSXMASXSAMMMMMAMSAMXMAAXSXMXMXMASMXXAMXAXXAAAMASMSSXSAMXXXMXXMXXXSAMASMASAMXXMSSSMSXSAAAMAAXMASMAAMXMMSSMAAAAXSMMAXMSMSSS
SAMXXAXAMMXMXAMXXXAAMMMMAMXAXMXAMXMMAMAMSMMXMMASASMSXMSAMSXMSSSMSASAAAAXXMXMASXXMAMXMAMXMXASXSMSMAAAAAAMMSMMSMMMAAMMMMMAMAXMMSMSMSAMAMXAAAAX
MASMSSMMSSMMSMSAMMMSSSSSSMSMMMSSSSXSAMXMMXMAAXAMXSXMAMSMMXAMMAAAMXMMMMMMXSASXMSAMSMXSMMXSMMSAMXAMMMMMMSMMAXMAAMSAMXMXAAXMAXSMMAAASAMAMMMMMSM
MASXAAXXAAAMAAAAMAXXAXAAXMAXAMXAXAASXSSXXASMSMMSMXMMSMMSMSSMMMMMSXSSXXMAMMAMAMSXMASAAAMMMSXSMMSMSXXXAMXXSXSSSXMMMMAMXMSXMAXXAMSMMXXMXMAXAAXA
MASMXSMMMSMMMMMMXXSMMMMMMSXSSSMXMMMXMAXASMMAAAAAMXXAAAXXMAMMAASASAAAXXASMMSMMXSXMAMSSMMSAXMXAASAMASAAMSAMXXXMAAXAXASASAMMSMSAMMXXXXMASMSMSSM
MASXAXAMAXAMXMMMMMMXAAXAAXMAMAMXXXMASAMMMAAMMASMMSMASMMMMSSMSXMASMMMMMXMXAMAXXMAAAMXXAAMASMMMMSAMAMSSMMAXMXASXMSSSXSMMASMAMMAMXAXSMMMAMAMXAX
SAMXXSAMASAMMMSAAXMASASMSXMMSMMMSMMAMAMXSXMXXXMXAASAAMSAXAAXXXMMMXAAAAAMMMSXMASXMMSASMMMMAAXAAXXMXMAXAMSAMMMAAMAXXMMXMSMMASXMMMMMSAAMASAMSAM
XAMAMMAMMMAMXASXSMXAXMSXXASAMAASAMMSMXMAXXMSXXAMMMSSMAXXMSSMSSSMMSSSSMXMAMAXSXMXAXMMMMSSSMXSMSMXMAMASXMXAXAMXAMASMXMAXMASXSAXSASASXMSMSMAMMM
SSSMMMSMSXSAMXMMXMMASAMASXMAMXMXASXAASMMSAASMMXMMAMAXMSSMAXAAXAXXXAAAXAASMMMMAXMMMMMMAAXAXAXAAXAMMSMXMASMSMSMSSXSAASMSSMMSMMMSAMASMAAAMAMXSX
AMAAMSMAMMMMSSMMAMMMMAMAMMSSMSMSMMMMXSAMXMXXXXAAMSSMMXAXSAMMMSMMAMSMMAMXMASXXMSXMAXAMXSSMMSSSMSSXXAMAXMMAMASAAXAXXXSXAAMSXSAAMAMMMASMSSSXMAS
MSSMMAMAMAXAAAAMXSASMXMASMAMAAAAXAXXAMAMXXMAXMXMXMAXSMMMSXSXXAXMMMAAXMXMSXMAAXMASMSMMAMAAAAXAAAAMSASXSMMXMAMMMMXMXXMMSMMAASMXXAMXAXXAAAAXSSX
XAMXXXXAMSMMSSXMMSASXXXXXMASMMSMSSSMXSAMMAAXSMSXMMMMAAXXXAMASXSAXSMSMXAAXSXSMMSAMXAAMSSSMMSMMMMSMMMMASAAAMXSAAMMMMMMMMAAMMMAMSMSSSSMMMMSAMXS
MMSMSSSMSAAMAXAMXMMMMMMMAMASAAXAAAMAMSMSXSSXAAAASAMXSMMMMSMXMASMXMXMAXMXAMMASAAAMSSSMAAASXMMSAAMMAAMXMASXSASXMSAMAAAMXXMSAMAMAAAAASXMXAMMSAX
AXMAAAAMSMSMSSSMSASAAAXAAMSSMMMMMSMAMMAMAMMXMMMXMASAMAAXAAMAMXMXAMSSSSXMAMSAMXXAMAAXMMSMMSXASMSSSXMMAXXMAAMMMXXAMMSMSAXMSASXMMSMMMMMMMXSXMAS
SMMMMSAMMAXAAAAAXASXSSMSXSAMXSAAAAMMXSAMAMSAMASMSMMMSSMSSSMMSASXSAAAMAASAMMASMSSMMSMXXMMAMMMMMMMAASXMMAMXMMSSMSSMMXMAXSASAMMXXAMXMASAMMMAMMM
MXSAMMXSMMMMMMMMMXMAXAMXMMMMMMMXSMMXAXASXMMASASAAMAAMAAXXMASMXMAMMMSMSMMAMSXSAAAXXAAMMAMSSXAAXAMMMMASXAMASAMXAAAMMAXAAMAMXAMMSASXMASASASASAS
SASMSXAMASAMAXAAMMMMSMMXMAAAAXXMMXSXASMMXSSMMMMXMSMMMMXMMMXMAAMSMXAMXMAXAXMAMMMSASXSXSAMAMMASXMSMMMAMSMMMMMXMMMSSSSMMSMXMMXSXSMMXMMSXMASASAS
MAMAMMMSASASMXSAMXAAAAAMSSSSSXSAAAMMMMAAAMMMASMXMMMSAMXMXMAMSMSAXMMSAMSSSSMAMAXMASAAASAMAMXMAMXAAAMXMAXAXAAAMAAAXMAAXAAAXXAMAXXAAMASAMAMAMAM
MAMAMAMMMSMMMMAMXMMMXSMAXMAAAASMMASAXSMMMSMSASAMXAASAMXMSSXXAXXMAXXMASXAAMMMXMSMXMMMMMMSSSSXSMSXMMMXSMSSMMSXSAMXSSSMMSSMMMAMAXMSMSASXMSMSMSM
SMSSSMSAMMMAXSSSSMXSXXXMAMMMMMMMSAXAMMAAAXXMASASMMMSAXAMMAMSXMAMSMSSMMMMMMAXASAMXXMMXSAAXXMAXASMSXXMAMAMAMXMAMMXAXAMXMMAXXSMMXXAAMMMAAMAMAAA
AAAXAXSAMAMMXMAAAXAXMAMSSMMMXMMMMXXSASXMMSAMXSXMAAXSXSSSMAMMMSMAAAMMMAXXASMSMXASMMSMAMMMMMAMMAMASAASAMASMMXMAMMXMSAMXSMXMAMAASXSSMMSMMMAMSMS
MMMSMMSXMSSMAMMMMMMSMMMXAAAXAAAASMXMASAAMXASAMXSSMXXMAXXXASAMAMSMMMXSAMMXMMAXSMMMAAMMSMSASAXMSMAMXMMASAMXAASASXAXAAMMSAAMAMMMSAAXXAAAXSMMMAM
MSAMXASAMXAMSMSAXAAAAAXSMMMSASMXSAAMASMMMXAMXSAMASXMXSXMMXSMSXXMMMSAMXSMAXSAMMAAMSSSXAAMMMSMSXMSSMMSAMXSMSXSAXMASMSMAXMXMXSXSMMMMMSSSMXSAMXM
XAAAMMXMMSXMXASASMXSSMMAAXXAXXXAMXMMXMMXSAMXMAXSAMXMMMAASMSAMMMAAXMASAAMAMMASXSXMMXMMMSMSAMXAXSAAAAMXSASMMAMAMXXAMXMXSMXSAMXMAMXSXMAMMAMMSAM
SSSMAMXSASASMMMXXXAXMMMSMMSMMSMAMAXXXAAAMAXSAXMMMMASAMXMSAXAXSSMMMSAMMAMXMXXAAMMMMAAMAMAMXSMMSMSSMMSAMMSAMXMXMMSSMXMASXAMASAMAMAXAMMMMSXXSXS
AAAXXXXMASMSAMMXSAMXAAAAAAXAAXMASXMASMMSSSMMMXMAAMAXASXXMMMSMXAASXMXSAMXMSMSMAMAASMSSMMMMSXASMAAMAAMXMASXMMXMXMAMAAMASMAXXXMXSMMSMMXAAASAMXM
MMMMSSMMMMXSAMSMSMXMSMXXMMMMMSSXSASXMMXMAXMASAXMSSSSSMMMMASXSXSMMAMXMMMAMAAAXASXMMAMXAAAMASMMMMMSSMSASMSAXMASAMAMMMMASXSASXSAXXXAMMXMMSAXMAS
XSXAAAXXMXAMAMSAXAAAXSSSSSMMSAXAMAMAAAAMMMSAMXSAAAAMMAAMSXSAMMMXXAMAXXXSSMSMSXSMSMAMSSMXSAMXASXMXMASASXMMSSSSXSAMASXMMMMMMAMASMSASAAMXMASXAA
AMMMSSMAXMMSSMMXMMMXMAXAAXASMSMMMSSSMMMXSAMAAAAMMMMMMMMXSAMXMAMASASXSXXMAMXXMXMAMSSMAAAXMASMXMASAMXMXMAXXAXAXMSAMMXAXXAXAMXMXMASMMMMSAMASMXM
MXSAMAXMXAMAXASXSXSXMMMMMMMMAMSXXAAMXMSAMASXMAXMAXAAXAXMSAMXMXSAXXAXAXSXXMSXSAMXMAXMMMMMSAMMMSMMMMXAMXSMMSMMMXSMMSSMMSSSSSXMMMMMMSAMXMMASAMS
SAMASAMMSMMMSMMAXAMAXXXAXMXMXMAMMMMMAXMASAMMMAMSMSMSSXSAMAMMXXMMSASMMMSAAAAASMSSMSSMSMSXMASAAAMASXMAXMAMAAAASXSMAAAAMAMAAXXAAAAAXSXMASMXMMAA
MAXMMMSAXAAAMMMSMMSSMMSSSMASASAXSXSXXMSAMMSMXAXAASAAAMMAMAXMMAAMAXXSAAMSMMMXMAMMAMXAAASXMASMSXSAXSAAASAMMMMMSAXMMSMMMXMSMMMSSSMSMMMAMXMAXMSM
XAMSAMXAMSMMSMAXAMAXAAAAAMASAXXMSASXAAXMXMAMMMSMSMMMSMXASXSMMASMMMAXXSMMMXMAMAMMXMASMSXAMAXMMXMMSSMMMSASXSSMMMMMXAMSXMAAAXXAMMXXMXXAMXMSXAXX
MMXSASMMMXAAAMXSSMAXMMSSMMMMMMAMMAMMMMMMASASAAXMAMAAXMSAXAAMAAMAXXAMXXMXMAXSSMSMAMXXXMXXMSSSMMSMAXAMASMMAMSAAXAXMASXASXSSMMAXXXMAMSASXAXMXMX
ASAMMAAASXMSSSMMMMSSSMXMXXSASMSMMXMXMXXSASASMAMSASMXSASASXXMMSSSMMAMSASXSXSAMMAMAXAAAXSXMAAAXSAMSSSMASAMMMMMMSMSSXMMMMAAXASAMSMXAMXSSMMSAXAM
SMASMMSMAAMAMXAMAMXAMSAMXMMASXMASMMSXAMMXMAMAXXMXSMXAMMAMXAXMXAXAXAMMAMAAXMAMSASMSSXSAMXMMSMMSASMAAMAMMSXSXMMAMAXAMXAMXMXXMAMSAMXSXXXAAXAMMA
XSAMXAXXSSMMMSMMMMMMMSXMASMAMASAMMAMAMMSSMMMXMMSAMXSMXMSMSMMSMMMXMAMMSMMMMSAMMASAMXMMMMSMAMXASMMMSMMSSXSASXXSAMASMSSMMASXXXXMMSMAXMAXMMSMSXS
AMMMMMSAMXAAAAMMMSAMXMASMSMSSMMMMMAMXXAAXAXMASAMMXAMXAAMAMXAXAMAMSAMAXAAAMMAMMAMMAAXXAAMMSSMXSAAXMXMXMAMAMAXSAMXXXAMXSASMMSAMAAMXSMSMMMAAXMM
XMASMAMMMSSMMMSAAMSXXAMXXMAMAAMASXMMMMSXSSMXXMSSXMXSSXSMMMMMSSMSASASASXMXMSSMMSMXMMXSMMSAMAMXSXMMSAMXMAMAMSMMAMAMMMSMMAXAMXAMSSMMMAAAASMSMAA
MSAMXSAMAXXAMAMMXMMSAMXMAMASMMMAAAAAXAMXMASAMXAXMASXXSXMASAMAXAXMSAMXSMXXMAMAAXMMMXMAMXMXSAMXMAMAXXXAXMMSXXASMMXSAAAXMSMXMSXMXMAAMMMSMXAMXXM
MMSSXMAMMSSSMXSAXSAMXSAMASXSMAMMSSMSMSSXSAMXMMMSXSXMMMSSXSMSASXMXMXMMMXMAMASMMSSMASMSMSAASXMASAMXSMMSXSAMXMMAMAAXMXSMXAAMMAAXAMSXMAMAXSMMSMS
SAAMMSAMAXAXSXMXXMASASAMAMAXXAMMMMAAXXAAMAMAASMMMMAMAAXXXMASAMXMXMMMAMAMXSASAAAAMSMAXAAMXSMSXSASXAAAAAMXMAXXAXMMMSAMXAMXAMSMMMXAXMXSAXMXMAAM
MMXSXSAMXMMMMMMMMSMMMSAMSSMSXSMSAMSMSMMMMASAMXAMAMXMAMMXXMAMAXXXAAAXAXXMAMMSMMSXMAMMMMMSAMAMASAMXSMMSSXMMSSSSMSAAAASAMXASXXAAMAMMMAMMMMAMMSM
SAXSXMXSAMAAAAMAAAAMXXAMXXXSMMAMXMAMXXMASXSAMXXMAXMXMSMXXMXSAMSSMSXSASMASMMXXXMXSSSXAXAXAXSMMMMSMMMXAAXMAMXAMAMMSSMMMMSSMMXMMSASAMAMSASXSMXX
MXSXAMAMMSSSSXSMSSSMXSSMSMXSAMAMAMAMSMMXXXMXMASMSMSAAAMMXSAMASXAAMMMMAMXMAMASMMMXAMAMMMSMMXXXXAAAASMSSSMASMMMSMAMMMXAAXAAAMSASAMXSAMMASAAXAX
MMSXMMASXMMAMMAAAXAMAXAAAXAXXMAXMSMMMASXMMSMMMSAAASMMMASAMASXXXSMXXMSSMASAMAXAASXMMSAAMAMAMSMMSXSMSAMAMMAMXMAXMSSMXMMXSMMMSMAMAMMMMSSMMXMMSX
XAXAXXXSAAMAMXXMXSMMSSMMMMSSSSSSXAMASAMASAAASXMXMMMXASXMASAMXMXXAMSXMASXXAMXSSMSAXAAMXSAMMAAAAXXXMMAMAMMMMAMMXAMAMSMSXXAAXXMXMAMAAAXAAAXXXMM
MSSXMASXXMMASXSAMXMAMMAAXXXAXAXXXMSMMASXMMMXMAAMXASMMMAMAXAXXMAMXMMASXMMXSAMXMAXMMMXXMSMSMSSMMSXMAMXMASAXSASMMMMMMSAMASXMMSSSMSSMXMASMMSSMSA
AXAAXXXMAXSASMAMSAMXSSSMMMMXMXMMAMAXMAMAAAMSMMMMSMSMMSAMSMMSMMAXAAMAMAMAAMAXSMXMXAXASMSAXAXXXXMAMSSMSXMAXXXAMXMASAMAMAMAAAXAAAAMXAMAXAXXMAXS
SMSAMXMASMMMMXAMMXXAMMMAAASMMSASMSXSMMMSMMXAAAXXAAXAASXMMAAAASASMXMMMAMMASMMMXMASXXXMAMMMSAMMMSMMAAXSAXSASXSAMXXMMSMMXSSMSMSMMMSSSSMSSMMMSMX
MMAMXSMAMAAXXMXSASMMSAXSMSAAASAMAXAMXMMXXMMSSMXSMXMMMSXMXMMSXMMSAASMSXSMAAMAXMAXXXASMSMXMMAAAAAXMMMMMXMAAAAXXSMXXMAMXMMXAXAXAMXXAMAMXAXXAMMM
MXMSSSXAMSMMAMMSAMXXMXXMMMMMMMAMAMXMXSAMASAXAMXXMSXSAMAXSAAMASAMXMAAXAXMMSSMMMMXMMXMAXAMXSSMMSMSMSAXXASMSMAMAAXMMSMSAASMAMSMASAMXXXMSMXMMSAA
SAMXAMSSXMSMAXAMMMSXMSXSAXAAXSSMMXSAMMAMAMXSMMAAAAXMAXMMAMXSXMSAMXMAMXMXAAAAAXSAMAAMSMSSMMAMMAAAAAAMSMMXMMAMSMAAAMXSMSXAAXASAMMSSXMAXXMXAMAX
SASMXMAXAASMMSSMSAMAMAAAMXSMMAAAAAMAMSSMMSAMXSSXMMXSMMSSMMMMXXXMASXSMAMMMSMMMXMASXXXAMXAXMAMSMSMSMSMSAMAXSXMASAMXXASXMMSMSMSXMMAXAMAXMAMSSSX
SAMXAMASXMMAMXMAMMXAMMMMXAMXMSSMMXSSMAAAAMASXMMSAXXXMAAAXXAXXAMMMMMXSAXAAMXSMSSMMMSASXMXMXMXMXAXXXAASMMMXMAMXAMXSAMSAXAAMMAMXSMSSXMASASXXAXM
MMMSMXAAAMSAMMMAMSMSSSMMMMSAXAMXMXSAMSSMMSSMMAASXXAAMMSSMSXSMXMXAAMMSXSXSMASAXXAAASAMXMSSXMAMXMASMMMMXXMAXXMMXSAXAMSMMSSMMAMXAAAAAXAXMMXMMMA
AMAMAMSSMMAMMXSSXSAXAMXAAAXMMASMMMSAMAAAAXAASMMSSMSSMAXAAXAXXASMSMSASMSAAMAMMMSSMMXAXXMAMMSMSAMAMASXMAXSSMMSMAMXSMMXXAXMASMSMMMMXSMSSMMAMMAX
XMAMXXMAAXXXMAMMAMXMASXMSSSMSASAAASXMSSMMSMMMMMXMXAMMXSMXMMMMXSAAXMXXAMXMMXXAMAMXXMSMSMAXMAASAMAXSMMMSXMAASXMASMMAASASMSMMAAAXASXMAMAASXSSMS
MSSMMASMMMMMMAXMMMSXXMAMAAAAMASMSMSMMXAMAXXAXMSAMMMSSMMMAAAXXXMXMMSMMSMSMMAMMMMSSXMMAASMMMMXSXMSXXMSAMAMSMMASXSAMXMSAMAAMSSMSMAMXSSMSMMAAAMX
XAAASMMXAAASMSSMAAMAMSSMMSMMMXMAMAMAXXAMMSSXSAMASAAAMAASXSMSSMMAXAAAMXAAAMSSMAAAMAMMXMSXMSXASMMMAMAMASMMMASXMASMMXXMAMSXMAAXXMXSMXAAXXXMSMMM
MMSMMAMSMSMSAXAXMSSMMAXAXXMXSAMAMAMSAXMMMXAMXASXMMMSSSMSXXMAAMSMMSSSMMMMMMAAMMMMXAMAMSMMMSMMMAAMMMAMASXMMAMASXSAXXASXMXMMSSMXMXMAXMMMXXXMAXX
MAXAXXMAAMXSMSMMMXXMXXXMMMSASASXSMXMMASAMXMASMMMMAMXXMASMSMXSXXXAXXAAMXAMXSMMXAXSMSASAAAXXSMXSMMAMXSXMAXMAMXMASAASMMMAMXAAMMSSMMMMAAXXXASMMS
MSSMMSMMSMAMMAAAXXXMASASXMMASAMASMXSXMSASASXXMMASAMXAMXMAAXSAXMMSMMSMMSSSMXSASXXAASXMMSMSSXSAAMSSSMSMSXMMMSMSXMMMSAASXSMMMSAAAAAXSSMSSMMMAAM
XMAXAAASAMMSMSXMMMASASAMXAMAMAMAMXXMAMMMMAMMAMXMXMSSMMAMSMSXAAMMASXMMAXAAAMSXAXSMXMASAXXXXAMSSMAMAAMASMSMAAAXXAXASAMAAAMSSMMSSMMXMAMAXAASMMX
XSAMXSMSASAAAMSMXSAMXSXMXSMSSSMXXAMSXMASMAMSSMSXSAMXAAAMAXXMMMXSAXMAMXSSMMMSXMASXAMXAASMMMMMMXMMSMMMMMAAMMMSMMXMASMSMAMXMASAXAAXAXAMXSMXSXSX
MMMSAMASXMMSXSAMXMASXMMSAXXMAXAMMMAAASASMSMMXAAAAXXSMSMSMSMAMSAMXXSAMXMXAMAXAXMMMXMAMSMAAAAAXMXMXXXAMMSMSMMXMMAMXMAXXXMASMMMSSMMMSXSASXMMAXS
MAASASAMAMAMMSAMXXAMXAAMASAMMMMMAMXSMMASMMAMMMMSMMAXAAAAAAMAMMASAXMASXMASMMSASASMSMAXAXSMXXMMXMMMMSMSAMMAASXMSMXAMSMMMSASXAMXMASXAXMAMASMMMX
SMMSMMAXXMAXAMMXSMMSSMMSXXAMXASXMSAXMSXSASMMAXXMASXMSMSMSMSSMSAMXSSMMAXAMXXAASAMAAXAMSXMASXSSMSMAAAXMASMSSMAAXAASXMAMAMASMXXXMAXSSXXAMAMAXAA
ASAMXSXMMSMSMAMAMXAAAXXXXSXMSXSAAMAMAMASAMXSSSXSAMMXMAAXAMXMMMMSMXAASXMMMMSMMMXMSMMXAMAMAMAASAAMSSMMMAMXMAXMMMMMMASXMAMAMMSXXMSXXMAMSSXSMMSA
AMMXMASAAAXAXAMMSSMSSMMSMSMASAMMMMAMXMAMAMMAMXAMAMXAMSMXMMXMXAMAMXMMMXAMAAXXXAXAAAXSXMAMAMMMMSMXMAMSSMMASMMMXAXASXMXSASAAXAMXAXSMXSAMXASXMAM
SXMMSXAMSSSSSXSAMAAAMXAAAMMAMAMMSSSSSMMSAMMSAMXSAMSAXMAMXMAMXMSASXMSSMSSMSMSXMMSMAMSASMSSSMMMMXAMAMMAMSASAAXMXMAXAAAXASMSMMAASMXMAXAAMAMAXMM
XAMAMXMAXXMAMMMASMMMSSSMSMMXSXMMMAAMXAASAMAMXMXSAMMMAMXAAMASAAMASAAAAAAAAAXSASMAMAAXAMAAAAXMASMSSSMMAMMXSMMXAAAMSMMAMXMAMAXSSMXAMXSASMAXSMMX
SMMASMXMXXMMMASAMXSAAAXAMXMXSXSAMMMMSMMSXMASAAMSXMMSAMMSXSASMSMASMMMXSMMMMMSAMSXMXSMSMMMSSMMASAXAAASMMSXMAXMSXMXAXSXSMMXMXMMAMSXSAMMXMSAMASM
AXMAXAAMSMSXSASXSXAMMSMMMASMSASXMSAXXMASASASMSAMAMAMASXMXMAXMXMASXASAXMSXMAMXMAXMSXMMAMAMAMAXMXMMMMMSAMXSMMAXXSMMMAAAAXMASMSAMMAMXMSAAXMSXMA
MSMSXXAMAAMAMASAMMMMAXAAXXSAMXMAMSASMXASAMASAXMXAMMXXMXMMMMSSMMXXMASMSAAAMSMXMAXSAAMXSMMXAMAMXMXSAXXMXMAAXAMSAMASXMXMSMMAXASXMMASMAMMSSXMASM
XXAMASXSMXMAMMMMMAXMSSMMSSMXMMXMXXXMMMXSMMMMMMSSMSXAXSAMXAXXAASXSMAMXMMMSMMAXAMXXAXMAXAXSAMSAMXAXXSXMASXMASXMAMAMAXSSMXASMMMAXSAMXXXSMMAXAMA
SMAMAMAAXASXSAAASMSMMAASXMAAXAAMMMMSXSMXXAXAXMXAMSMMSAAMSMSSSMMAXMAMXMMXXAMMMMMMMSMMXSAMSXMASAMMSMAMAMXSMXXAMAMAXXMMAAMMXAAMAMMASXXXMAMSMXSM
AAAMAMMMMMXAMMXMSXMASXMSAMSMSSMSAAXAAXMASMMSXXSAMXAMAXMMMAMAXMMMMSMSSMSXMAMAAXXAAAAXAMAMXASAMMMMAXXSXMAAMAMASMSMSMMSMMMXSMMMSSSXMXMMMSMAXMAX
SSMSXXAAAXMMMSSMMXSAMXAXXMAMAMASXSMMSMMXMMMXMMSMMMXMAXXXMAMXMMXMAMMAAMAASXMSMSAMSMMMXMASMXMASASMMMASAMXAMXSAMMAXAMXXAXXXMMAXMXMXAMXSAMXAMMXM
MAMXASMMMXMMAAAMAMMASMMMSSMMAMMMXXAMXAXAXAASAAXAXAXMMSSMMMSMAXAMXSMSSMSXMAXAMXAMAXMSMSASAMXAMXMAASMSXMSXMXMASXSSMSSSMMXMASMMSAMMXMAXASMSSSMM
SAMMXMAASAMXMSXMAMSAMXAAXASMMMXMAXASMSMAMMSSMMXXMMAXAAMAAAAAMSMSXAAAMMXSAMXAXXAMXSMAAMAXMAMXSAMMMMAXAMXAAXSSMAXAXAAAXAXMAMXAMAMASMXMAMAAAMAX
SAMXXXMASAXMXXASAXXMASMMSMMMSSSMMSAMAMAXMSAMASXMMSSMMSSSMMSSXAAMXMMMSXSAMXSSMSSMAXMMMMXMXMSASXXMAAMSAMMSAMXXMSSMMSMMMSXMASMSSSMAMAXMMMMMSMMM
XAXSAMXMSXMSASAMXSAMAXAAXXAAMXAAAMXMAMXXXXASAMXAXAAAMAMXSXAXXMMXAMXMAMXMAMXXAAAMXSSXMXAMAXMXSAXSAMXMAXAXASMSAMXXAXASXMAMXMAXXASXMSAMXAAAAAXA
MSMMASXMSMXMASAMXXAMXMMMXSMSSXMMXMMSASMMMSXMAXMSMSSMMMSAMMMMXSASXSSMSMSXMXXMMMSAMXXAMSASMXMXMXMAAMASMMXSMAAMASAMSSMSASMMSMMMMMAXAXASASMMXSXX
MXAXAMAMMSAMXMASXSSMMSASAXMAMXSXMMAMAMAAAXMXSXAAAXAXAAMASMXSXMASAAAAAAMXXMMXAAAAMASMMMASAASXMMASMMMAAMXMMAXMASAMXXASAMMAAAAAAXMMAMAMAAXXSMMX
SMXMXMXAASMSAMXSXSAAXSAMXSMSMXSASMASASXMXSXAMMSMSMMSMXSAMAASAMXMMMMSMSMMAMXAMMSAMASXXXAMXMSAMAMMXXMXAMXMMSSMXSAMMMMMAXMXSSMMXXXMASAMXMAXAAXX
AASXMAMXMSASMMAXMXMMMMMMMMAAAAMAMMAXXSXMSMMASAMAAAXAAXMMSMAMXSAAAXXMXMMSASXSSXMAMSSXXMASAMSAMSMSMMXSMSXSAAAXAMAAXAXMAMSMMMMSMMXSASMXMXMSMSMX
MSMAASMSMMAMAMASAAXXXAAAMMSMSXMMMMMXMSAMAASAMMSSSSMMSMMAXXAMXSXSMSAMAXXSMMMAMXXAMXMXMSAXXMXAMMAAAMMAMXAMMSSMSSXMSXXMSMMAMMAAAAXMASXXAAXAMXAX
XAMXMMAXSMXSMMXAXMSMSMSXSXAAAASAMXMAMXASXMMASAAMAAXAMAMSSSMSAMXXASMMASAMXMMSMMSMSXMAMMSSSSSMMMSMSMAAXMXMXXMAXAXXXXXXMASMMMSSXMXMASMSSSSMMMSX
MMAXMMXMXSAMXMXMXMAAMAMASMMSMXSASASMSMMMMXSXMMSSSXMXSSMMAMXMMSASMMSMAMASXASAMAAAAXSAMSAXMAXAAAXXMMSMMSSMMSSSMSMSASMXSAMASXAXAMXMXMAXAXAAAAMM
AXSAMAXMMMMSAMMXASMMSAMAMAXAMMSAMASAAXSSSMXAMXMAMMSMAAXMXMXXXMMSAMXMSSXMMMSASMMSSXSXSAMXMAMMMMMXXAAAXXAAAAAAAXAMXMAASASAMMAXMXMASMSMMMSMMMSA
SMAASXSMAAASMMAMXSAAMAMMMXMMXAMXMMMXMASAAXSSMSXAAASASMMSSSMMSAMXMMXXXXAMAXSAMXMAMAMMSMXXMSXSASAAMSSSMSSMMMSMMMSMXMMMSXMAMMMMSAXAXMXMAAXAMAMX
XAMXMAAASXXSASMSAMMMSXSMMXMXMMMMSAMXXSXSMMSAAMXMMASAMXXAAAXXAAASMSXXMSMMSMMMSMMMSXMASXXXMAAMAMMSMAAAMAMAMMMAXXAXSXMMMMSSXXMASASXSMASMSSXMAMX
MSSMMSMMMMXSAMAMAXAAAASAAASASMSASASMMMAMXXXMMMXMMXMAMAMMSMMSSSMSAMXXMAMAXMAXMAXMXMMXSMSSMMSMAMAXMMSMMASMMAMSMSMSXMSAAMAMMSSMMXMAAMAXMMMMSMSM
AXAAAMASXXAMAMXMXAMSMXMMSXSASAAXSXXAAXAMSAMXAAAXAASMMAAXMAXAAAAMMMXMMAMASMSMSAMSAMXAMXAMAAXMXMASXAXXSMSASASAAAMXXASMSMMSAAAXSAMSMMSXSAAAAAAA
XSSMMSAMXMXSXMASXXXXXMAXXMMXMMMAXMSSMSASXSASXSSSSMXSSSSMSSMMSMMMAXMASXSMSAMXMXMSAXMASMSSMMSAMXXXMSMMAMXMSSSMSMSMXXMSXMXMMSSMSMMMSAMXSSSSMSMS")

(define test-input-string "MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX")

(define (count-xmasses-HF string)
  (let loop
    ((str string)
     (count 0))
    (let ((i (match str "XMAS")))
          
      (if (not i)
          count
          (loop (substring str (+ i 2)) (+ count 1))))))

(define (count-xmasses-HB string)
  (let loop
    ((str string)
     (count 0))
    (let ((i (match str "SAMX")))
          
      (if (not i)
          count
          (loop (substring str (+ i 2)) (+ count 1))))))

(define (string-split str delimiter)
  (let loop ((s str) (parts '()))
    (let ((pos (string-index s (string-ref delimiter 0)))) ; Find the first delimiter
      (if pos
          (loop (substring s (+ pos 1)) 
                (append parts (list (substring s 0 pos))))
          (append parts (list s)))))) ; Add the last piece

(define (string-index s char)
  (let loop ((i 0))
    (if (< i (string-length s))
        (if (char=? (string-ref s i) char)
            i
            (loop (+ i 1)))
        #f)))

(define (string-join strings sep)
  (if (null? strings)
      ""
      (let loop ((rest (cdr strings)) (result (car strings)))
        (if (null? rest)
            result
            (loop (cdr rest) (string-append result sep (car rest)))))))

(define (transpose-string rect-str)
  (let* ((lines (string-split rect-str "\n"))
         (columns (apply map list (map string->list lines))))
    (string-join (map list->string columns) "\n")))

(define (angle-diagonally rect-str)
  (let* ((lines (string-split rect-str "\n")) ; Split the input into rows
         (rows (map string->list lines))          ; Convert each row to a list of chars
         (height (length rows))
         (width (length (car rows))))
    (let loop ((n 1) (result '()))                ; Start from diagonal 1
      (if (> n (+ height width -1))               ; Stop when all diagonals are processed
          (string-join (reverse result) "\n")     ; Combine all rows into the final string
          (let ((diagonal (get-diagonal rows n height width))) ; Get the nth diagonal
            (loop (+ n 1) (cons (list->string diagonal) result)))))))

(define (get-diagonal rows n height width)
  "Extract the nth diagonal from a rectangular grid of rows."
  (let* ((start-row (if (<= n width) 0 (- n width))) ; Start at the appropriate row
         (start-col (if (<= n width) (- n 1) (- width 1)))) ; Start at the appropriate column
    (let loop ((r start-row) (c start-col) (diagonal '()))
      (if (or (< r 0) (< c 0) (>= r height) (>= c width)) ; Stop if out of bounds
          (reverse diagonal)                              ; Return the diagonal
          (loop (+ r 1) (- c 1) (cons (list-ref (list-ref rows r) c) diagonal))))))

(define (switch-row-order rect-str)
  (let* ((lines (string-split rect-str "\n"))) ; Split into rows
    (string-join (reverse lines) "\n"))) 

; part 1

(define (total-count string)
  (let ((t-string (transpose-string string))
        (ar-string (angle-diagonally string))
        (al-string (angle-diagonally (switch-row-order string))))
    (+
     (count-xmasses-HF string) ; horizontal LtoR
     (count-xmasses-HB string) ; horizontal RtoL
     (count-xmasses-HF t-string) ; vertical downwards
     (count-xmasses-HB t-string) ; vertical upwards
     (count-xmasses-HF ar-string) ; diagonal downwards RtoL
     (count-xmasses-HB ar-string) ; diagonal upwards LtoR
     (count-xmasses-HF al-string) ; diagonal upwards RtoL
     (count-xmasses-HB al-string) ; diagonal downwards LtoR
     )))

(define count (total-count input-string))
    
; part 2

(define (make-matrix string)
  (let* ((lst (string-split string "\n"))
         (x (length lst))
         (y (string-length (car lst)))
         (v (make-vector x 0)))
    (let loop
      ((i 0)
       (list lst))
      (if (= i x)
          v
          (begin
            (vector-set! v i (string->vector (car list)))
            (loop (+ i 1) (cdr list)))))))

(define (matrix-ref matrix x y)
  (vector-ref (vector-ref matrix x) y))

(define (matrix-set! matrix x y in)
  (vector-set! (vector-ref matrix x) y in))

(define result-matrix (make-matrix input-string))

(define (get-submatrix matrix i j)
  (let ((matrix-out (make-vector 3 0)))
    (let loop
      ((a 0))
      (cond ((= a 3)
             matrix-out)
            (else
             (vector-set! matrix-out a (vector
                                        (matrix-ref matrix (+ i a) j)
                                        (matrix-ref matrix (+ i a) (+ j 1))
                                        (matrix-ref matrix (+ i a) (+ j 2))))
             (loop (+ a 1))))))) 

(define (check-submatrix matrix) ; returns 0 or 1 to add to the count
  (cond ((not (eq? (matrix-ref matrix 1 1) #\A))
         0)
        ((and (eq? (matrix-ref matrix 0 0) #\S)
              (eq? (matrix-ref matrix 2 2) #\M))
         (cond ((and (eq? (matrix-ref matrix 0 2) #\M)
                     (eq? (matrix-ref matrix 2 0) #\S)) 1)
               ((and (eq? (matrix-ref matrix 0 2) #\S)
                     (eq? (matrix-ref matrix 2 0) #\M)) 1)
               (else 0)))
        ((and (eq? (matrix-ref matrix 0 0) #\M)
              (eq? (matrix-ref matrix 2 2) #\S))
         (cond ((and (eq? (matrix-ref matrix 0 2) #\M)
                     (eq? (matrix-ref matrix 2 0) #\S)) 1)
               ((and (eq? (matrix-ref matrix 0 2) #\S)
                     (eq? (matrix-ref matrix 2 0) #\M)) 1)
               (else 0)))
        (else 0)))

(define (count-x matrix)
  (let ((x (vector-length matrix))
        (y (vector-length (vector-ref matrix 0))))
    (let loop
      ((i 0)
       (j 0)
       (count 0))
      (cond ((= (+ i 2) x)
             (loop 0 (+ j 1) count))
            ((= (+ j 2) y)
             count)
            (else
             (loop (+ i 1) j (+ count (check-submatrix (get-submatrix matrix i j)))))))))

(define count-2 (count-x result-matrix))


